FROM ubuntu:22.04
RUN apt update -y \
&& apt install libc-bin libc6 libgdbm-compat4 libgdbm6 libnet-ssleay-perl libperl5.34 libssl3 libwhisker2-perl netbase perl perl-base perl-modules-5.34 perl-openssl-defaults git python3 \
&& git clone https://github.com/sullo/nikto.git
