FROM ubuntu:latest
RUN apt update -y && apt install -y libgdbm-compat4 libgdbm6 libnet-ssleay-perl libperl5.30 libwhisker2-perl netbase perl perl-modules-5.30 perl-openssl-defaults git python3 \
&& git clone https://github.com/sullo/nikto.git
